global:

  # Scrape targets every five seconds (default: one minute)
  # This enables data to be gathered quickly for this demonstration
  scrape_interval: 5s

  # Also evaluate alerting rules every five seconds
  # (This will be useful later in this guide)
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080